from enum import StrEnum


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EdgeType(StrEnum):
    SOURCE_IMPORT = "SOURCE_IMPORT"
    PACKAGE_DEPENDENCY = "PACKAGE_DEPENDENCY"
    CONFIG_REFERENCE = "CONFIG_REFERENCE"
    BUILD_DEPENDENCY = "BUILD_DEPENDENCY"
    ROUTE_REFERENCE = "ROUTE_REFERENCE"
    TEST_REFERENCE = "TEST_REFERENCE"
    DYNAMIC_IMPORT = "DYNAMIC_IMPORT"
    SELF_IMPORT = "SELF_IMPORT"


class FileClassification(StrEnum):
    ENTRYPOINT = "ENTRYPOINT"
    FRAMEWORK_ENTRYPOINT = "FRAMEWORK_ENTRYPOINT"
    CLI_SCRIPT = "CLI_SCRIPT"
    EXAMPLE = "EXAMPLE"
    TEST = "TEST"
    CONFIGURATION = "CONFIGURATION"
    DOCUMENTATION = "DOCUMENTATION"
    GENERATED = "GENERATED"
    SOURCE_MODULE = "SOURCE_MODULE"
    ORPHAN_CANDIDATE = "ORPHAN_CANDIDATE"
    ROUTE = "ROUTE"


class GraphQualityStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    POOR = "POOR"


class TestAnalysisState(StrEnum):
    COVERAGE_VERIFIED = "COVERAGE_VERIFIED"
    TEST_RELATIONSHIP_VERIFIED = "TEST_RELATIONSHIP_VERIFIED"
    STRUCTURAL_GAP_INFERRED = "STRUCTURAL_GAP_INFERRED"


class AIProviderKind(StrEnum):
    OPENAI_COMPATIBLE = "openai_compatible"
    OLLAMA = "ollama"
    CUSTOM_REST = "custom_rest"
    GROQ = "groq"
    NVIDIA = "nvidia"
    OPENROUTER = "openrouter"


class AnalysisTrigger(StrEnum):
    COMMIT_COMPARISON = "commit_comparison"
    BRANCH_COMPARISON = "branch_comparison"
    PULL_REQUEST = "pull_request"
    ZIP_UPLOAD = "zip_upload"


class StatementType(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    RECOMMENDATION = "RECOMMENDATION"


class RecommendationType(StrEnum):
    EVIDENCE_BACKED = "EVIDENCE_BACKED"
    POLICY_BASED = "POLICY_BASED"
    GENERIC_BEST_PRACTICE = "GENERIC_BEST_PRACTICE"


class CalibrationStatus(StrEnum):
    NOT_CALIBRATED = "NOT_CALIBRATED"
    PRELIMINARY = "PRELIMINARY"
    CALIBRATED = "CALIBRATED"

